# -*- coding: utf-8 -*-
"""Emotion_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vkHIL3D2djOVHn_IgwzBNZfKGtXpXe6S
"""

! pip install transformers -q

from transformers import pipeline

emotion = pipeline('sentiment-analysis', model='arpanghoshal/EmoRoBERTa')

emotion_labels = emotion("I feel very depressed")

flag=0

emotion_labels



if emotion_labels[0]['label'] == 'anger' and emotion_labels[0]['score'] >= 0.9:
  flag=1

if emotion_labels[0]['label'] == 'annoyance' and emotion_labels[0]['score'] >= 0.9:
  flag=1



if emotion_labels[0]['label'] == 'nervousness' and emotion_labels[0]['score'] >= 0.65:
  flag=1

if emotion_labels[0]['label'] == 'fear' and emotion_labels[0]['score'] >= 0.65:
  flag=1

if emotion_labels[0]['label'] == 'desire' and emotion_labels[0]['score'] >= 0.9:
  flag=1

if emotion_labels[0]['label'] == 'sadness' and emotion_labels[0]['score'] >= 0.7:
  flag=1

if emotion_labels[0]['label'] == 'grief' and emotion_labels[0]['score'] >= 0.7:
  flag=1

if emotion_labels[0]['label'] == 'remorseness' and emotion_labels[0]['score'] >= 0.7:
  flag=1

print(flag)